apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260624-224621-pw1is2pfsshv-service
spec:
  selector:
    app: enterprise-system-20260624-224621-pw1is2pfsshv
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
